In [31]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score

In [32]:
data = pd.read_csv("../dataset.csv")
data

/tmp/ipykernel_17879/323681850.py:1: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../dataset.csv")

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,Normal,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,Normal,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,Normal,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,Normal,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,59.166.0.8,12520,149.171.126.6,31010,tcp,FIN,0.020383,320,1874,31,...,0,8,20,7,5,1,1,4,Normal,0
699997,59.166.0.0,18895,149.171.126.9,80,tcp,FIN,1.402957,19410,1087890,31,...,0,1,1,2,7,2,2,2,Normal,0
699998,59.166.0.0,30103,149.171.126.5,5190,tcp,FIN,0.007108,2158,2464,31,...,0,13,13,6,7,2,1,2,Normal,0
699999,59.166.0.6,30388,149.171.126.5,111,udp,CON,0.004435,568,304,31,...,0,10,13,6,5,1,1,3,Normal,0
700000,59.166.0.0,6055,149.171.126.5,54145,tcp,FIN,0.072974,4238,60788,31,...,0,13,13,6,7,1,1,2,Normal,0

In [33]:
data['ct_flw_http_mthd'].fillna(data['ct_flw_http_mthd'].max(), inplace=True)
data['is_ftp_login'].fillna(data['is_ftp_login'].max(), inplace=True)
data['ct_ftp_cmd'] = pd.to_numeric(data['ct_ftp_cmd'], errors='coerce', downcast='integer')
data['ct_ftp_cmd'].value_counts(dropna=False)

0    686192
1     10472
2      1168
4       800
3       729
6       332
5       290
8        18
Name: ct_ftp_cmd, dtype: int64

In [34]:
data = data.drop(['srcip','sport', 'dstip', 'dsport','Label','Stime', 'Ltime'], axis = 1)

In [35]:
data['ct_ftp_cmd'].fillna(data['ct_ftp_cmd'].max(), inplace=True)
data['ct_ftp_cmd'] = data['ct_ftp_cmd'].astype(int)

In [36]:
resultNa = data.isna()
count = resultNa.sum()
count

proto               0
state               0
dur                 0
sbytes              0
dbytes              0
sttl                0
dttl                0
sloss               0
dloss               0
service             0
Sload               0
Dload               0
Spkts               0
Dpkts               0
swin                0
dwin                0
stcpb               0
dtcpb               0
smeansz             0
dmeansz             0
trans_depth         0
res_bdy_len         0
Sjit                0
Djit                0
Sintpkt             0
Dintpkt             0
tcprtt              0
synack              0
ackdat              0
is_sm_ips_ports     0
ct_state_ttl        0
ct_flw_http_mthd    0
is_ftp_login        0
ct_ftp_cmd          0
ct_srv_src          0
ct_srv_dst          0
ct_dst_ltm          0
ct_src_ ltm         0
ct_src_dport_ltm    0
ct_dst_sport_ltm    0
ct_dst_src_ltm      0
attack_cat          0
dtype: int64

In [37]:
data['attack_cat'].unique()

array(['Normal', 'Exploits', 'Reconnaissance', 'DoS', 'Generic',
       'Shellcode', ' Fuzzers', 'Worms', 'Backdoors', 'Analysis'],
      dtype=object)

In [38]:
categorical_columns = ['proto', 'state', 'service', 'attack_cat']
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

In [39]:
data

,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,...,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat
0,120,2,0.001055,132,164,31,29,0,0,2,...,0,0,3,7,1,3,1,1,1,6
1,120,2,0.036133,528,304,31,29,0,0,0,...,0,0,2,4,2,3,1,1,2,6
2,120,2,0.001119,146,178,31,29,0,0,2,...,0,0,12,8,1,2,2,1,1,6
3,120,2,0.001209,132,164,31,29,0,0,2,...,0,0,6,9,1,1,1,1,1,6
4,120,2,0.001169,146,178,31,29,0,0,2,...,0,0,7,9,1,1,1,1,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,114,5,0.020383,320,1874,31,29,1,2,0,...,0,0,8,20,7,5,1,1,4,6
699997,114,5,1.402957,19410,1087890,31,29,2,370,5,...,0,0,1,1,2,7,2,2,2,6
699998,114,5,0.007108,2158,2464,31,29,6,6,0,...,0,0,13,13,6,7,2,1,2,6
699999,120,2,0.004435,568,304,31,29,0,0,0,...,0,0,10,13,6,5,1,1,3,6
700000,114,5,0.072974,4238,60788,31,29,7,30,0,...,0,0,13,13,6,7,1,1,2,6

In [40]:
y = data['attack_cat']
X = data.drop(columns=['attack_cat'])
X

,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,...,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm
0,120,2,0.001055,132,164,31,29,0,0,2,...,0,0,0,3,7,1,3,1,1,1
1,120,2,0.036133,528,304,31,29,0,0,0,...,0,0,0,2,4,2,3,1,1,2
2,120,2,0.001119,146,178,31,29,0,0,2,...,0,0,0,12,8,1,2,2,1,1
3,120,2,0.001209,132,164,31,29,0,0,2,...,0,0,0,6,9,1,1,1,1,1
4,120,2,0.001169,146,178,31,29,0,0,2,...,0,0,0,7,9,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,114,5,0.020383,320,1874,31,29,1,2,0,...,0,0,0,8,20,7,5,1,1,4
699997,114,5,1.402957,19410,1087890,31,29,2,370,5,...,4,0,0,1,1,2,7,2,2,2
699998,114,5,0.007108,2158,2464,31,29,6,6,0,...,0,0,0,13,13,6,7,2,1,2
699999,120,2,0.004435,568,304,31,29,0,0,0,...,0,0,0,10,13,6,5,1,1,3
700000,114,5,0.072974,4238,60788,31,29,7,30,0,...,0,0,0,13,13,6,7,1,1,2

In [41]:
df = pd.DataFrame(X)

scaler = StandardScaler()
standarized_data = scaler.fit_transform(df)
standarized_data

array([[ 0.53956355, -1.60983126, -0.03324893, ..., -0.36637035,
        -0.28184255, -0.53731325],
       [ 0.53956355, -1.60983126, -0.03189644, ..., -0.36637035,
        -0.28184255, -0.08506951],
       [ 0.53956355, -1.60983126, -0.03324647, ...,  0.16808864,
        -0.28184255, -0.53731325],
       ...,
       [-0.08423805,  0.54384848, -0.03301555, ...,  0.16808864,
        -0.28184255, -0.08506951],
       [ 0.53956355, -1.60983126, -0.03311861, ..., -0.36637035,
        -0.28184255,  0.36717423],
       [-0.08423805,  0.54384848, -0.03047597, ..., -0.36637035,
        -0.28184255, -0.08506951]])

In [42]:
data_columns = X.columns.tolist()
scaled_df = pd.DataFrame(standarized_data, columns=data_columns)
scaled_df

,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,...,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm
0,0.539564,-1.609831,-0.033249,-0.108637,-0.258887,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.201221,-0.141476,-0.111842,-0.666038,0.208351,-0.843012,-0.398264,-0.366370,-0.281843,-0.537313
1,0.539564,-1.609831,-0.031896,-0.099817,-0.258135,-0.187861,-0.097889,-0.335726,-0.329448,-0.610013,...,-0.201221,-0.141476,-0.111842,-0.863077,-0.438814,-0.575663,-0.398264,-0.366370,-0.281843,-0.085070
2,0.539564,-1.609831,-0.033246,-0.108325,-0.258812,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.201221,-0.141476,-0.111842,1.107311,0.424072,-0.843012,-0.636947,0.168089,-0.281843,-0.537313
3,0.539564,-1.609831,-0.033243,-0.108637,-0.258887,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.201221,-0.141476,-0.111842,-0.074922,0.639794,-0.843012,-0.875630,-0.366370,-0.281843,-0.537313
4,0.539564,-1.609831,-0.033245,-0.108325,-0.258812,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.201221,-0.141476,-0.111842,0.122117,0.639794,-0.843012,-0.875630,-0.366370,-0.281843,-0.537313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,-0.084238,0.543848,-0.032504,-0.104449,-0.249696,-0.187861,-0.097889,-0.282693,-0.298552,-0.610013,...,-0.201221,-0.141476,-0.111842,0.319156,3.012732,0.761079,0.079101,-0.366370,-0.281843,0.819418
699997,-0.084238,0.543848,0.020804,0.320730,5.587483,-0.187861,-0.097889,-0.229659,5.386309,1.338676,...,4.725848,-0.141476,-0.111842,-1.060116,-1.085979,-0.575663,0.556466,0.168089,0.419414,-0.085070
699998,-0.084238,0.543848,-0.033016,-0.063513,-0.246525,-0.187861,-0.097889,-0.017525,-0.236760,-0.610013,...,-0.201221,-0.141476,-0.111842,1.304349,1.502680,0.493730,0.556466,0.168089,-0.281843,-0.085070
699999,0.539564,-1.609831,-0.033119,-0.098926,-0.258135,-0.187861,-0.097889,-0.335726,-0.329448,-0.610013,...,-0.201221,-0.141476,-0.111842,0.713233,1.502680,0.493730,0.079101,-0.366370,-0.281843,0.367174
700000,-0.084238,0.543848,-0.030476,-0.017186,0.066958,-0.187861,-0.097889,0.035509,0.133992,-0.610013,...,-0.201221,-0.141476,-0.111842,1.304349,1.502680,0.493730,0.556466,-0.366370,-0.281843,-0.085070

In [43]:
concat_df = pd.concat([scaled_df,y], axis=1)
concat_df

,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,...,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat
0,0.539564,-1.609831,-0.033249,-0.108637,-0.258887,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.141476,-0.111842,-0.666038,0.208351,-0.843012,-0.398264,-0.366370,-0.281843,-0.537313,6
1,0.539564,-1.609831,-0.031896,-0.099817,-0.258135,-0.187861,-0.097889,-0.335726,-0.329448,-0.610013,...,-0.141476,-0.111842,-0.863077,-0.438814,-0.575663,-0.398264,-0.366370,-0.281843,-0.085070,6
2,0.539564,-1.609831,-0.033246,-0.108325,-0.258812,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.141476,-0.111842,1.107311,0.424072,-0.843012,-0.636947,0.168089,-0.281843,-0.537313,6
3,0.539564,-1.609831,-0.033243,-0.108637,-0.258887,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.141476,-0.111842,-0.074922,0.639794,-0.843012,-0.875630,-0.366370,-0.281843,-0.537313,6
4,0.539564,-1.609831,-0.033245,-0.108325,-0.258812,-0.187861,-0.097889,-0.335726,-0.329448,0.169462,...,-0.141476,-0.111842,0.122117,0.639794,-0.843012,-0.875630,-0.366370,-0.281843,-0.537313,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,-0.084238,0.543848,-0.032504,-0.104449,-0.249696,-0.187861,-0.097889,-0.282693,-0.298552,-0.610013,...,-0.141476,-0.111842,0.319156,3.012732,0.761079,0.079101,-0.366370,-0.281843,0.819418,6
699997,-0.084238,0.543848,0.020804,0.320730,5.587483,-0.187861,-0.097889,-0.229659,5.386309,1.338676,...,-0.141476,-0.111842,-1.060116,-1.085979,-0.575663,0.556466,0.168089,0.419414,-0.085070,6
699998,-0.084238,0.543848,-0.033016,-0.063513,-0.246525,-0.187861,-0.097889,-0.017525,-0.236760,-0.610013,...,-0.141476,-0.111842,1.304349,1.502680,0.493730,0.556466,0.168089,-0.281843,-0.085070,6
699999,0.539564,-1.609831,-0.033119,-0.098926,-0.258135,-0.187861,-0.097889,-0.335726,-0.329448,-0.610013,...,-0.141476,-0.111842,0.713233,1.502680,0.493730,0.079101,-0.366370,-0.281843,0.367174,6
700000,-0.084238,0.543848,-0.030476,-0.017186,0.066958,-0.187861,-0.097889,0.035509,0.133992,-0.610013,...,-0.141476,-0.111842,1.304349,1.502680,0.493730,0.556466,-0.366370,-0.281843,-0.085070,6

In [44]:
concat_df.to_csv('../../cleaned_dataset_v2.csv', index=False)